### ISSUE TITLE
default subnetが設定されない

### ISSUE THREAD

**Issue by yterauchi** [primecloud-controller-org/primecloud-controller#48]
サーバviewにてインスタンスを新規作成した場合、データベースにてAWS_CERTIFICATE.DEF_SUBNETにsubnet IDが値が入っていたとしても、「EDIT」-「詳細」をみても、値が設定されていない。
そのため、インスタンスの新規作成をしたあと、そのまま「Start」ボタンを押しても、インスタンスは起動しない。
新規インスタンスを起動するためには、必ず「EDIT」-「詳細」からsubnetを指定しなければならない。

同じく、サービスviewから、サービスととサーバを同時に作成しても、そのままサービスの起動はできない。

**Comment by ymstmsys** [comment]
修正完了しました。
